//DATA MESAS
export const GET_DATA_MESAS = "GET_DATA_MESAS";
export const ERROR_DATA_MESAS = "ERROR_DATA_MESAS";
export const PUT_DATA_MESAS = "PUT_DATA_MESAS";
export const DELETE_DATA_MESAS = "DELETE_DATA_MESAS";
export const POST_DATA_MESAS = "POST_DATA_MESAS";
